#!/bin/bash
# Populate ~/.config the way Omarchy's install/config/*.sh does, adapted for Ubuntu.
set -eEo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

mkdir -p ~/.config ~/.local/bin ~/.local/state/omarchy/toggles/hypr

# 1. Hyprland: the stock autogenerated config is replaced (backed up); anything
#    else the user wrote in ~/.config/hypr is kept.
if [[ -f ~/.config/hypr/hyprland.conf ]] && grep -q '^autogenerated = 1' ~/.config/hypr/hyprland.conf; then
  log "Backing up stock Hyprland config to ~/.config/hypr/hyprland.conf.pre-omarchy"
  mv ~/.config/hypr/hyprland.conf ~/.config/hypr/hyprland.conf.pre-omarchy
fi

# 2. This repo's own config overrides win over Omarchy's defaults
install_tree "$OMBUNTU_REPO/config" ~/.config

# 3. Omarchy's ~/.config payload, minus the pieces that don't apply on Ubuntu
#    (fcitx5 input method, chromium flags, Arch-only autostart entries).
skip='^(fcitx5|environment.d|autostart|chromium|chromium-flags.conf|Typora|wiremix|omarchy.ttf)$'
for entry in "$OMARCHY_PATH"/config/*; do
  name=$(basename "$entry")
  [[ $name =~ $skip ]] && continue
  if [[ -d $entry ]]; then
    install_tree "$entry" ~/.config/"$name"
  else
    install_file "$entry" ~/.config/"$name"
  fi
done

# 4. Shell: Omarchy's bashrc (starship, eza, zoxide, aliases). Backed up once.
if [[ $OMARCHY_SKIP_BASHRC != true ]] && ! grep -q 'omarchy/default/bash/rc' ~/.bashrc 2>/dev/null; then
  log "Installing Omarchy bashrc (previous one saved as ~/.bashrc.pre-omarchy)"
  [[ -f ~/.bashrc ]] && cp -a ~/.bashrc ~/.bashrc.pre-omarchy
  cp "$OMARCHY_PATH/default/bashrc" ~/.bashrc
fi

# 5. XCompose (Caps Lock is the compose key in Omarchy's Hyprland input config)
if [[ ! -f ~/.XCompose ]]; then
  name=$(git config --global user.name 2>/dev/null || true)
  email=$(git config --global user.email 2>/dev/null || true)
  cat >~/.XCompose <<XC
# Run omarchy-restart-xcompose to apply changes

# Include fast emoji access
include "%H/.local/share/omarchy/default/xcompose"

# Identification
<Multi_key> <space> <n> : "$name"
<Multi_key> <space> <e> : "$email"
XC
fi

# 6. Persistent toggles + branding text (About / screensaver)
[[ -f ~/.local/state/omarchy/toggles/hypr/flags.conf ]] || cp "$OMARCHY_PATH/default/hypr/toggles/flags.conf" ~/.local/state/omarchy/toggles/hypr/
mkdir -p ~/.config/omarchy/branding ~/.config/omarchy/themes
cp -f "$OMBUNTU_REPO/branding/about.txt" ~/.config/omarchy/branding/about.txt
cp -f "$OMBUNTU_REPO/branding/screensaver.txt" ~/.config/omarchy/branding/screensaver.txt

# 7. Desktop entries, icons, web apps and TUIs (Omarchy's own refresher)
omarchy-refresh-applications >/dev/null 2>&1 || warn "omarchy-refresh-applications reported errors (non-fatal)"

# 8. Walker + Elephant wiring (mirrors install/config/walker-elephant.sh upstream)
mkdir -p ~/.config/autostart ~/.config/systemd/user/app-walker@autostart.service.d ~/.config/elephant/menus
cp -f "$OMARCHY_PATH/default/walker/walker.desktop" ~/.config/autostart/
cp -f "$OMARCHY_PATH/default/walker/restart.conf" ~/.config/systemd/user/app-walker@autostart.service.d/restart.conf
for menu in omarchy_themes omarchy_background_selector omarchy_unlocks; do
  ln -snf "$OMARCHY_PATH/default/elephant/$menu.lua" ~/.config/elephant/menus/$menu.lua
done

# 9. User services: SwayOSD (from Omarchy) gated to Hyprland sessions so it does
#    not crash-loop under the XFCE X11 session; battery monitor timer.
mkdir -p ~/.config/systemd/user/swayosd-server.service.d
cat >~/.config/systemd/user/swayosd-server.service.d/hyprland-only.conf <<'UNIT'
[Unit]
ConditionEnvironment=XDG_CURRENT_DESKTOP=Hyprland
UNIT
systemctl --user daemon-reload || true
systemctl --user enable swayosd-server.service elephant.service >/dev/null 2>&1 || true
systemctl --user enable omarchy-battery-monitor.timer >/dev/null 2>&1 || true

# 10. Default applications, scoped to the Hyprland session only so the XFCE
#     session keeps its own defaults. (GLib and xdg-utils both read
#     $XDG_CURRENT_DESKTOP-mimeapps.list; case differs, so provide both.)
bash "$OMBUNTU_REPO/install/mimeapps.sh"

# 11. uwsm reads ~/.config/uwsm/env with /bin/sh (dash), so always install the POSIX version
cp -f "$OMBUNTU_REPO/config/uwsm/env" ~/.config/uwsm/env

# 12. Ubuntu's waybar/hypridle/foot/hyprpolkitagent packages ship user services that
#     systemd enables by default. Omarchy starts these itself from Hyprland's autostart,
#     so the services only produce duplicates (two bars, two idle daemons).
# (they are enabled globally by the packages in /etc/systemd/user, so a per-user mask is required)
systemctl --user mask --now waybar.service hypridle.service foot-server.socket foot-server.service hyprpolkitagent.service >/dev/null 2>&1 || true

# 13. XFCE's notification daemon is D-Bus activated and collides with Mako under Hyprland
mkdir -p ~/.config/systemd/user/xfce4-notifyd.service.d
cat >~/.config/systemd/user/xfce4-notifyd.service.d/not-under-hyprland.conf <<'UNIT'
[Unit]
ConditionEnvironment=!XDG_CURRENT_DESKTOP=Hyprland
UNIT
systemctl --user daemon-reload || true

# 14. Xubuntu's MATE polkit agent autostart entry fails under Hyprland (hyprpolkitagent already
#     holds the agent registration); hide it for this session only
if [[ -f /etc/xdg/autostart/polkit-mate-authentication-agent-1.desktop ]]; then
  sed 's/^NotShowIn=.*/&Hyprland;/' /etc/xdg/autostart/polkit-mate-authentication-agent-1.desktop >~/.config/autostart/polkit-mate-authentication-agent-1.desktop
  grep -q '^NotShowIn=' ~/.config/autostart/polkit-mate-authentication-agent-1.desktop || echo 'NotShowIn=Hyprland;' >>~/.config/autostart/polkit-mate-authentication-agent-1.desktop
fi

# 15. Ombuntu naming in the places the user sees it
sed -i 's/"Omarchy Menu\\n/"Ombuntu Menu\\n/; s/Omarchy update available/Ubuntu updates available/' ~/.config/waybar/config.jsonc
sed -i 's/echo \\"Omarchy \$version\\"/echo \\"Ombuntu (Omarchy $version)\\"/' ~/.config/fastfetch/config.jsonc
ln -sfn "$OMARCHY_PATH/bin/omarchy" ~/.local/bin/ombuntu

# 16. Default terminal for xdg-terminal-exec (Alacritty, like Omarchy)
[[ -f ~/.config/xdg-terminals.list ]] || cp "$OMARCHY_PATH/config/xdg-terminals.list" ~/.config/

# 17. GTK primary-paste like Omarchy's first-run
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true 2>/dev/null || true
