#!/bin/bash
# shellcheck disable=SC2154  # hw_* variables come from eval of detect-hardware.py
# Populate ~/.config the way Omarchy's install/config/*.sh does, adapted for Ubuntu.
set -eEo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

mkdir -p ~/.config ~/.local/bin ~/.local/state/omarchy/toggles/hypr

# 1. Hyprland: the stock autogenerated config is replaced (backed up); anything
#    else the user wrote in ~/.config/hypr is kept.
if [[ -f ~/.config/hypr/hyprland.conf ]] && grep -q '^autogenerated = 1' ~/.config/hypr/hyprland.conf; then
  log "Backing up stock Hyprland config to ~/.config/hypr/hyprland.conf.pre-omarchy"
  mv ~/.config/hypr/hyprland.conf ~/.config/hypr/hyprland.conf.pre-omarchy
fi

# 2. Hardware-derived defaults for a first install: display scaling from the panel's
#    EDID, keyboard layout from the system/XFCE keyboard settings. Only written when the
#    user has no monitors.conf / no active kb_layout yet; never overwritten afterwards.
hw=$(python3 "$OMBUNTU_REPO/install/detect-hardware.py") || die "Hardware detection failed (install/detect-hardware.py)"
eval "$(sed 's/^/hw_/' <<<"$hw")"
: "${hw_scale:=1}" "${hw_gdk_scale:=1}" "${hw_panel:=none}" "${hw_kb_layout:=}" "${hw_kb_variant:=}"
[[ $hw_kb_layout =~ ^[A-Za-z0-9,_-]*$ && $hw_kb_variant =~ ^[A-Za-z0-9,_-]*$ ]] || { warn "Ignoring unusual keyboard layout value"; hw_kb_layout=""; hw_kb_variant=""; }
[[ $hw_scale =~ ^[0-9.]+$ && $hw_gdk_scale =~ ^[0-9.]+$ ]] || { hw_scale=1; hw_gdk_scale=1; }
if [[ ! -f ~/.config/hypr/monitors.conf ]]; then
  mkdir -p ~/.config/hypr
  sed -e "s/^env = GDK_SCALE,1$/env = GDK_SCALE,$hw_gdk_scale/" -e "s/^monitor=,preferred,auto,1$/monitor=,preferred,auto,$hw_scale/" \
    "$OMBUNTU_REPO/overlay/config/hypr/monitors.conf" >~/.config/hypr/monitors.conf
  sed -i "1i # Detected at install: $hw_panel -> scale $hw_scale (edit freely; see the examples below)" ~/.config/hypr/monitors.conf
  record ~/.config/hypr/monitors.conf
  log "Display scaling: $hw_scale ($hw_panel)"
fi

# 3. This repo's own config overrides win over Omarchy's defaults
install_tree "$OMBUNTU_REPO/config" ~/.config

# 3b. Omarchy's ~/.config payload, minus the pieces that don't apply on Ubuntu
#    (fcitx5 input method, chromium flags, Arch-only autostart entries).
skip='^(fcitx5|environment.d|autostart|chromium|chromium-flags.conf|Typora|wiremix|omarchy.ttf|omarchy)$'  # omarchy/: hook + extension samples, not supported
for entry in "$OMARCHY_PATH"/config/*; do
  name=$(basename "$entry")
  [[ $name =~ $skip ]] && continue
  if [[ -d $entry ]]; then
    install_tree "$entry" ~/.config/"$name"
  else
    install_file "$entry" ~/.config/"$name"
  fi
done

# 3c. Keyboard layout into Hyprland's input.conf (Omarchy's file has it commented out)
if [[ -n $hw_kb_layout && $hw_kb_layout != us ]] && ! grep -qE '^\s*kb_layout\s*=' ~/.config/hypr/input.conf 2>/dev/null; then
  sed -i "/^[[:space:]]*kb_options *=/i\  kb_layout = $hw_kb_layout" ~/.config/hypr/input.conf
  [[ -n $hw_kb_variant ]] && sed -i "/^[[:space:]]*kb_options *=/i\  kb_variant = $hw_kb_variant" ~/.config/hypr/input.conf
  log "Keyboard layout: $hw_kb_layout ${hw_kb_variant:+($hw_kb_variant)}"
fi

# 4. Shell: Omarchy's bashrc (starship, eza, zoxide, aliases). Backed up once.
if [[ $OMARCHY_SKIP_BASHRC != true ]] && ! grep -q 'omarchy/default/bash/rc' ~/.bashrc 2>/dev/null; then
  log "Installing Omarchy bashrc (previous one saved as ~/.bashrc.pre-omarchy)"
  [[ -f ~/.bashrc ]] && cp -a ~/.bashrc ~/.bashrc.pre-omarchy
  cp "$OMARCHY_PATH/default/bashrc" ~/.bashrc
fi

# 5. XCompose (Caps Lock is the compose key in Omarchy's Hyprland input config)
if [[ ! -f ~/.XCompose ]]; then
  name=$(git config --global user.name 2>/dev/null || true)
  email=$(git config --global user.email 2>/dev/null || true)
  cat >~/.XCompose <<XC
# Run omarchy-restart-xcompose to apply changes

# Include fast emoji access
include "%H/.local/share/omarchy/default/xcompose"

# Identification
<Multi_key> <space> <n> : "$name"
<Multi_key> <space> <e> : "$email"
XC
fi

# 6. Remove hook/extension sample dirs an earlier install may have copied (not supported)
rm -rf ~/.config/omarchy/hooks ~/.config/omarchy/extensions ~/.config/omarchy/themed/alacritty.toml.tpl.sample

# 6b. Persistent toggles + branding text (About / screensaver)
[[ -f ~/.local/state/omarchy/toggles/hypr/flags.conf ]] || cp "$OMARCHY_PATH/default/hypr/toggles/flags.conf" ~/.local/state/omarchy/toggles/hypr/
mkdir -p ~/.config/omarchy/branding ~/.config/omarchy/themes
cp -f "$OMBUNTU_REPO/branding/about.txt" ~/.config/omarchy/branding/about.txt
cp -f "$OMBUNTU_REPO/branding/screensaver.txt" ~/.config/omarchy/branding/screensaver.txt

# 7. Desktop entries, icons, web apps and TUIs (Omarchy's own refresher). Ombuntu's
#    web app list leaves out Omarchy's own-company apps (HEY, Basecamp, Fizzy); drop any an
#    earlier run created, and the HEY bindings.
rm -f ~/.local/share/applications/{HEY,Basecamp,Fizzy}.desktop ~/.local/share/applications/icons/{HEY,Basecamp,Fizzy}.png
sed -i '/omarchy-launch-webapp "https:\/\/app\.hey\.com/d' ~/.config/hypr/bindings.conf 2>/dev/null || true
omarchy-refresh-applications >/dev/null 2>&1 || warn "omarchy-refresh-applications reported errors (non-fatal)"

#    The refresh recreates upstream's web apps every run. Where the human also has the real
#    application installed, the launcher then lists the same name twice; the native entry wins.
#    Only names from upstream's own list are considered, so web apps the human made are safe.
while IFS= read -r webapp; do
  entry=~/.local/share/applications/"$webapp".desktop
  [[ -f $entry ]] || continue
  grep -q "omarchy-launch-webapp\|omarchy-webapp-handler" "$entry" || continue
  native=""
  for dir in /usr/share/applications /var/lib/snapd/desktop/applications /var/lib/flatpak/exports/share/applications; do
    [[ -d $dir ]] || continue
    while IFS= read -r candidate; do
      # NoDisplay entries are URL handlers and the like: invisible in the launcher, so they
      # replace nothing. /usr/share/applications/google-maps-geo-handler.desktop is one.
      grep -qiE '^(NoDisplay|Hidden)=true' "$candidate" && continue
      native=$candidate
      break
    done < <(grep -rlx "Name=$webapp" "$dir" 2>/dev/null)
    [[ -n $native ]] && break
  done
  [[ -n $native ]] || continue
  rm -f "$entry" ~/.local/share/applications/icons/"$webapp".png
  log "Web app $webapp dropped: $(basename "$native") provides it natively"
done < <(sed -n 's/^omarchy-webapp-install "\([^"]*\)".*/\1/p' "$OMARCHY_PATH/install/packaging/webapps.sh" 2>/dev/null)
update-desktop-database ~/.local/share/applications 2>/dev/null || true

# 8. Walker + Elephant wiring (mirrors install/config/walker-elephant.sh upstream)
mkdir -p ~/.config/autostart ~/.config/systemd/user/app-walker@autostart.service.d ~/.config/elephant/menus
cp -f "$OMARCHY_PATH/default/walker/walker.desktop" ~/.config/autostart/
cp -f "$OMARCHY_PATH/default/walker/restart.conf" ~/.config/systemd/user/app-walker@autostart.service.d/restart.conf
for menu in omarchy_themes omarchy_background_selector omarchy_unlocks; do
  ln -snf "$OMARCHY_PATH/default/elephant/$menu.lua" ~/.config/elephant/menus/$menu.lua
done

# 9. User services: SwayOSD (from Omarchy) gated to Hyprland sessions so it does
#    not crash-loop under the XFCE X11 session; battery monitor timer.
mkdir -p ~/.config/systemd/user/swayosd-server.service.d
cat >~/.config/systemd/user/swayosd-server.service.d/hyprland-only.conf <<'UNIT'
[Unit]
ConditionEnvironment=XDG_CURRENT_DESKTOP=Hyprland
UNIT
systemctl --user daemon-reload || true
systemctl --user enable swayosd-server.service elephant.service >/dev/null 2>&1 || true
systemctl --user enable omarchy-battery-monitor.timer >/dev/null 2>&1 || true

# 10. Default applications, scoped to the Hyprland session only so the XFCE
#     session keeps its own defaults. (GLib and xdg-utils both read
#     $XDG_CURRENT_DESKTOP-mimeapps.list; case differs, so provide both.)
bash "$OMBUNTU_REPO/install/mimeapps.sh"

# 11. uwsm reads ~/.config/uwsm/env with /bin/sh (dash), so always install the POSIX version
cp -f "$OMBUNTU_REPO/config/uwsm/env" ~/.config/uwsm/env

# 12. Ubuntu's waybar/hypridle/foot/hyprpolkitagent packages ship user services that
#     systemd enables by default. Omarchy starts these itself from Hyprland's autostart,
#     so the services only produce duplicates (two bars, two idle daemons).
#     swaync is a different case: it is not part of Ombuntu, but the Hyprland PPA pulls it in,
#     and its unit claims the same BusName as mako's, which makes systemd refuse to load either.
#     Masking it is a no-op where it is absent. mako.service is left alone: it is D-Bus activated,
#     not enabled, so it is only a fallback if Omarchy's own mako ever dies.
# (they are enabled globally by the packages in /etc/systemd/user, so a per-user mask is required)
systemctl --user mask --now waybar.service hypridle.service foot-server.socket foot-server.service hyprpolkitagent.service swaync.service >/dev/null 2>&1 || true

# 13. XFCE's notification daemon is D-Bus activated and collides with Mako under Hyprland
mkdir -p ~/.config/systemd/user/xfce4-notifyd.service.d
cat >~/.config/systemd/user/xfce4-notifyd.service.d/not-under-hyprland.conf <<'UNIT'
[Unit]
ConditionEnvironment=!XDG_CURRENT_DESKTOP=Hyprland
UNIT
systemctl --user daemon-reload || true

# 14. Xubuntu session services that collide under Hyprland, hidden for this session only:
#     - the MATE polkit agent: hyprpolkitagent already holds the agent registration
#     - Ayatana's indicator service: it takes org.kde.StatusNotifierWatcher, and then every
#       tray item registers with it instead of waybar, whose tray stays empty
for entry in polkit-mate-authentication-agent-1 ayatana-indicator-application; do
  [[ -f /etc/xdg/autostart/$entry.desktop ]] || continue
  sed 's/^NotShowIn=.*/&Hyprland;/' "/etc/xdg/autostart/$entry.desktop" >~/.config/autostart/"$entry".desktop
  grep -q '^NotShowIn=' ~/.config/autostart/"$entry".desktop || echo 'NotShowIn=Hyprland;' >>~/.config/autostart/"$entry".desktop
done

# 15. Ombuntu naming in the places the user sees it
sed -i 's/"Omarchy Menu\\n/"Ombuntu Menu\\n/; s/Omarchy update available/Ubuntu updates available/' ~/.config/waybar/config.jsonc
sed -i 's/"text": "version=$(omarchy-version); echo \\"[^"]*\\""/"text": "ombuntu-version"/' ~/.config/fastfetch/config.jsonc
# About screen logo in Ombuntu purple (truecolor SGR), not Omarchy green
sed -i 's/"color": { "1": "[^"]*" }/"color": { "1": "38;2;136;25;252" }/' ~/.config/fastfetch/config.jsonc
sed -i 's/"keyColor": "[^"]*"/"keyColor": "38;2;136;25;252"/g' ~/.config/fastfetch/config.jsonc
# ...and the usage percentages, which fastfetch colours green by default (yellow/red warnings stay)
python3 - <<'PY'
import json, os
p = os.path.expanduser("~/.config/fastfetch/config.jsonc")
try:
    c = json.load(open(p))
except Exception:
    raise SystemExit(0)
c.setdefault("display", {}).setdefault("percent", {})["color"] = {"green": "38;2;136;25;252", "yellow": "yellow", "red": "red"}
json.dump(c, open(p, "w"), indent=2, ensure_ascii=False)
open(p, "a").write("\n")
PY
ln -sfn "$OMARCHY_PATH/bin/omarchy" ~/.local/bin/ombuntu

# 15b. Existing installs: screen-share tokens off, no 1Password binding (both were Omarchy defaults)
[[ -f ~/.config/hypr/xdph.conf ]] && sed -i 's/allow_token_by_default = true/allow_token_by_default = false/' ~/.config/hypr/xdph.conf
sed -i '/uwsm-app -- 1password$/d' ~/.config/hypr/bindings.conf 2>/dev/null || true

# 16. Electron/Chromium apps only use the GNOME keyring when they recognise the desktop;
#     under Hyprland they silently fall back to plain-text storage, which makes Signal
#     unable to open a database created under XFCE ("file is not a database").
#     Force the libsecret backend in Signal's launcher and Omarchy's Super+Shift+G binding.
if [[ -f /usr/share/applications/signal-desktop.desktop ]]; then
  sed 's|^Exec=\(\S*\)|Exec=\1 --password-store=gnome-libsecret|' /usr/share/applications/signal-desktop.desktop >~/.local/share/applications/signal-desktop.desktop
fi
sed -i 's|"uwsm-app -- signal-desktop"|"uwsm-app -- signal-desktop --password-store=gnome-libsecret"|' ~/.config/hypr/bindings.conf
#     Same for Chromium-family browsers (saved passwords vanish otherwise). Launcher entries
#     get an override here; Ombuntu's omarchy-launch-browser/-webapp add the flag too.
for entry in vivaldi-stable google-chrome brave-browser microsoft-edge chromium; do
  src=/usr/share/applications/$entry.desktop
  [[ -f $src ]] || continue
  sed 's|^Exec=\(\S*\)|Exec=\1 --password-store=gnome-libsecret|' "$src" >~/.local/share/applications/$entry.desktop
done
update-desktop-database ~/.local/share/applications 2>/dev/null || true

# 17. Beginner cheatsheet: app entry plus Super+Shift+K
mkdir -p ~/.local/share/ombuntu
cp -f "$OMBUNTU_REPO/docs/cheatsheet.html" ~/.local/share/ombuntu/cheatsheet.html
mkdir -p ~/.local/share/ombuntu/assets && cp -f "$OMBUNTU_REPO/logo/ombuntu-logo.png" ~/.local/share/ombuntu/assets/ombuntu-logo.png
cp -f "$OMBUNTU_REPO/logo/ombuntu-logo.png" ~/.local/share/ombuntu/ombuntu-logo.png
mkdir -p ~/.local/share/icons/hicolor/512x512/apps
cp -f "$OMBUNTU_REPO/logo/ombuntu-512.png" ~/.local/share/icons/hicolor/512x512/apps/ombuntu.png
gtk-update-icon-cache -q ~/.local/share/icons/hicolor 2>/dev/null || true
cat >~/.local/share/applications/ombuntu-cheatsheet.desktop <<'DESK'
[Desktop Entry]
Type=Application
Name=Ombuntu Cheatsheet
Comment=Keyboard shortcuts for beginners
Exec=ombuntu-cheatsheet
Icon=ombuntu
Terminal=false
Categories=Documentation;
DESK
grep -q 'ombuntu-cheatsheet' ~/.config/hypr/bindings.conf || printf '\n# Ombuntu beginner cheatsheet\nbindd = SUPER SHIFT, K, Cheatsheet, exec, ombuntu-cheatsheet\n' >>~/.config/hypr/bindings.conf
update-desktop-database ~/.local/share/applications 2>/dev/null || true

# 18. Browsers draw their own minimize/maximize/close buttons under Wayland. Switch the
#     Chromium family to system decorations so Hyprland (which draws none) leaves a clean
#     tab strip. Reversible with: ombuntu-browser-decorations on
[[ $OMBUNTU_KEEP_BROWSER_BUTTONS == true ]] || ombuntu-browser-decorations off || true

# 19. Default terminal for xdg-terminal-exec (Alacritty, like Omarchy)
[[ -f ~/.config/xdg-terminals.list ]] || cp "$OMARCHY_PATH/config/xdg-terminals.list" ~/.config/

# 20. No usage statistics or problem reports from the desktop
if [[ $OMBUNTU_KEEP_TELEMETRY != true ]]; then
  gsettings set org.gnome.desktop.privacy send-software-usage-stats false 2>/dev/null || true
  gsettings set org.gnome.desktop.privacy report-technical-problems false 2>/dev/null || true
fi

# 21. With apport disabled and whoopsie removed, Ubuntu's crash-notification helper
#     exits 1 (its script does `which whoopsie` under set -e), and uwsm's failed-unit
#     monitor would report that as an error. Nothing to notify about, so mask it.
systemctl --user mask update-notifier-crash.path update-notifier-crash.service >/dev/null 2>&1 || true
systemctl --user reset-failed update-notifier-crash.service >/dev/null 2>&1 || true

# 22. GTK primary-paste like Omarchy's first-run
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true 2>/dev/null || true
